name: Python lint
run-name: Pyright linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          python -m pip install pyright
          pip install -r requirements.txt
      - name: Run pyright
        run: pyright ./FreeFlyBot
